{% set name = "flake8-spellcheck" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-spellcheck-{{ version }}.tar.gz
  sha256: 17e539e9299dcc595f812e9f7233e12c413bdd4b2e614621aaa06e289605bb6a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8 >3.0.0
    - importlib_resources >=3
    - python >=3.6

test:
  imports:
    - flake8_spellcheck
  commands:
    - pip check
    - flake8 --version | grep flake8-spellcheck
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/MichaelAquilina/flake8-spellcheck
  summary: Spellcheck variables, comments and docstrings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
