{% set name = "flake8-spellcheck" %}
{% set version = "0.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8-spellcheck-{{ version }}.tar.gz
  sha256: 6fb79724f27097af0b4c678c7eaf731f0d87cf4c1eae7fbd7836c1c78d67e12c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - flake8 >3.0.0
    - python >={{ python_min }}

test:
  imports:
    - flake8_spellcheck
  commands:
    - pip check
    - flake8 --version | grep flake8-spellcheck
  requires:
    - flake8
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MichaelAquilina/flake8-spellcheck
  summary: Spellcheck variables, comments and docstrings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
